language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
script:
  - mvn install
  - mvn test
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
