/*DB Initialization */
INSERT INTO PRICING_POLICY (ID, FORMULA)
VALUES(1, 'FixedAmount + (HourlyRate * Hours)');


INSERT INTO PRICING_POLICY (ID, FORMULA)
VALUES(2, 'FixedAmount * Hours');


INSERT INTO PRICING_POLICY_PRICES
VALUES(1, 5, 'FixedAmount');


INSERT INTO PRICING_POLICY_PRICES
VALUES(1, 3, 'HourlyRate');


INSERT INTO PRICING_POLICY_PRICES
VALUES(2, 5, 'FixedAmount');


INSERT INTO PARKING (ID, NAME, PRICING_POLICY_ID)
VALUES(1, 'Q-Park Antibes Centre', 2);


INSERT INTO PARKING (ID, NAME, PRICING_POLICY_ID)
VALUES(2,'Parking Nice Etoile', 1);


INSERT INTO PARKING_SLOT (SLOT_ID, PARKING_ID, SLOT_TYPE, IS_AVAILABLE)
VALUES (1, 1, 'STD', TRUE);


INSERT INTO PARKING_SLOT (SLOT_ID, PARKING_ID, SLOT_TYPE, IS_AVAILABLE)
VALUES (2, 1, 'STD', TRUE);


INSERT INTO PARKING_SLOT (SLOT_ID, PARKING_ID, SLOT_TYPE, IS_AVAILABLE)
VALUES (3, 1, 'STD', TRUE);


INSERT INTO PARKING_SLOT (SLOT_ID, PARKING_ID, SLOT_TYPE, IS_AVAILABLE)
VALUES (4, 1, 'EC_50KW', TRUE);


INSERT INTO PARKING_SLOT (SLOT_ID, PARKING_ID, SLOT_TYPE, IS_AVAILABLE)
VALUES (5, 2, 'EC_50KW', TRUE);


INSERT INTO PARKING_SLOT (SLOT_ID, PARKING_ID, SLOT_TYPE, IS_AVAILABLE)
VALUES (6, 2, 'EC_20KW', TRUE);


INSERT INTO PARKING_SLOT (SLOT_ID, PARKING_ID, SLOT_TYPE, IS_AVAILABLE)
VALUES (7, 2, 'EC_20KW', TRUE);